worker_processes 1;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 64;
}

http {
    access_log /dev/stdout;
    client_max_body_size 2m;
    client_body_buffer_size 16k;
    client_body_in_file_only on;
    client_body_temp_path /capture;
    proxy_temp_path /tmp/nginx-proxy;
    fastcgi_temp_path /tmp/nginx-fastcgi;
    uwsgi_temp_path /tmp/nginx-uwsgi;
    scgi_temp_path /tmp/nginx-scgi;

    server {
        listen 14000 ssl;
        server_name acmeproxy;
        ssl_certificate /etc/nginx/tls/acmeproxy.crt;
        ssl_certificate_key /etc/nginx/tls/acmeproxy.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass https://pebble:14000;
            proxy_ssl_trusted_certificate /etc/nginx/tls/pebble-minica.pem;
            proxy_ssl_verify on;
            proxy_ssl_verify_depth 2;
            proxy_ssl_name pebble;
            proxy_ssl_server_name on;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
        }
    }
}
